#!/bin/bash
# Research deep dive - daily Wikipedia random + news

set -o pipefail

export PATH=/usr/bin:$PATH

LOG_DIR="/root/.openclaw/workspace/cron-logs"
DIARY_DIR="/root/.openclaw/workspace/diary"
LOG_FILE="$LOG_DIR/research-$(date +%Y%m%d-%H%M%S).log"

mkdir -p "$DIARY_DIR"

echo "=== Research Deep Dive: $(date) ===" > "$LOG_FILE"

# Helper: Log
log() {
    echo "[$(date '+%H:%M:%S')] $1" >> "$LOG_FILE"
    echo "$1"
}

# Helper: Fetch with retry
fetch() {
    local url="$1"
    local retries=3
    for i in $(seq 1 $retries); do
        result=$(curl -sL --max-time 30 "$url" 2>&1)
        if [ $? -eq 0 ] && [ -n "$result" ]; then
            echo "$result"
            return 0
        fi
        sleep 2
    done
    return 1
}

log "Starting research session..."

# Wikipedia Random Articles
log "Fetching Wikipedia random articles..."
WIKI_ARTICLES=""
for i in 1 2 3; do
    # Get random article
    RANDOM_URL=$(curl -sL -o /dev/null -w '%{url_effective}' "https://en.wikipedia.org/wiki/Special:Random" 2>/dev/null)
    if [ -n "$RANDOM_URL" ]; then
        TITLE=$(echo "$RANDOM_URL" | sed 's/.*\/wiki\///' | sed 's/_/ /g' | sed 's/%20/ /g')
        log "Article $i: $TITLE"
        WIKI_ARTICLES="${WIKI_ARTICLES}- $TITLE\n"
    fi
    sleep 1
done

# News from multiple sources
log "Fetching recent news..."
NEWS_ITEMS=""

# Hacker News top stories
HN_STORIES=$(curl -s "https://hacker-news.firebaseio.com/v0/topstories.json" 2>/dev/null | jq -r '.[0:5] | .[]' 2>/dev/null)
for story_id in $HN_STORIES; do
    STORY=$(curl -s "https://hacker-news.firebaseio.com/v0/item/${story_id}.json" 2>/dev/null)
    TITLE=$(echo "$STORY" | jq -r '.title // empty')
    URL=$(echo "$STORY" | jq -r '.url // empty')
    if [ -n "$TITLE" ]; then
        log "HN: $TITLE"
        NEWS_ITEMS="${NEWS_ITEMS}- [$TITLE]($URL)\n"
    fi
    sleep 0.5
done

# Write to diary
DIARY_FILE="$DIARY_DIR/$(date +%Y-%m-%d)-research.md"

cat > "$DIARY_FILE" << EOF
# Research Notes - $(date +%Y-%m-%d)

## Wikipedia Random Articles

$(echo -e "$WIKI_ARTICLES")

## Tech News (Hacker News)

$(echo -e "$NEWS_ITEMS")

## Thoughts/Connections

*Add insights here...*

---
*Generated by research cron job*
EOF

log "Written to $DIARY_FILE"

# Summary
log "=== Summary ==="
log "Wikipedia articles: 3"
log "News items: 5"
log "Diary file: $DIARY_FILE"
log "Research complete"
