#!/bin/bash
# Research deep dive - daily Wikipedia random + LIVE news

set -o pipefail

export PATH=/usr/bin:$PATH

LOG_DIR="/root/.openclaw/workspace/cron-logs"
DIARY_DIR="/root/.openclaw/workspace/diary"
LOG_FILE="$LOG_DIR/research-$(date +%Y%m%d-%H%M%S).log"

mkdir -p "$DIARY_DIR"

echo "=== Research Deep Dive: $(date) ===" > "$LOG_FILE"

# Helper: Log
log() {
    echo "[$(date '+%H:%M:%S')] $1" >> "$LOG_FILE"
    echo "$1"
}

log "Starting research session..."

# Wikipedia Random Articles
log "Fetching Wikipedia random articles..."
WIKI_ARTICLES=""
for i in 1 2 3; do
    RANDOM_URL=$(curl -sL -o /dev/null -w '%{url_effective}' "https://en.wikipedia.org/wiki/Special:Random" 2>/dev/null)
    if [ -n "$RANDOM_URL" ]; then
        TITLE=$(echo "$RANDOM_URL" | sed 's/.*\/wiki\///' | sed 's/_/ /g' | sed 's/%20/ /g')
        log "Article $i: $TITLE"
        WIKI_ARTICLES="${WIKI_ARTICLES}- $TITLE\n"
    fi
    sleep 1
done

# LIVE NEWS SOURCES
log "Fetching LIVE news from multiple sources..."
NEWS_ITEMS=""

# 1. Hacker News (always fresh, API)
log "Checking Hacker News..."
HN_STORIES=$(curl -s "https://hacker-news.firebaseio.com/v0/topstories.json" 2>/dev/null | jq -r '.[0:5] | .[]' 2>/dev/null)
for story_id in $HN_STORIES; do
    STORY=$(curl -s "https://hacker-news.firebaseio.com/v0/item/${story_id}.json" 2>/dev/null)
    TITLE=$(echo "$STORY" | jq -r '.title // empty')
    URL=$(echo "$STORY" | jq -r '.url // empty')
    if [ -n "$TITLE" ]; then
        log "  HN: ${TITLE:0:60}..."
        NEWS_ITEMS="${NEWS_ITEMS}- [HN] $TITLE\n"
    fi
    sleep 0.3
done

# 2. TechCrunch - extract titles from HTML
log "Checking TechCrunch..."
TC_RAW=$(curl -sL --max-time 15 "https://techcrunch.com/latest/" 2>/dev/null)
if [ -n "$TC_RAW" ]; then
    # Extract article titles
    echo "$TC_RAW" | grep -oE 'class="post-block__title__link"[^\u003e]*\u003e[^\u003c]+' | \
        sed 's/.*\u003e//' | head -3 | while read -r title; do
        [ -n "$title" ] && log "  TC: ${title:0:60}..." && NEWS_ITEMS="${NEWS_ITEMS}- [TC] $title\n"
    done
fi

# 3. The Verge
log "Checking The Verge..."
VERGE_RAW=$(curl -sL --max-time 15 "https://www.theverge.com/" 2>/dev/null)
if [ -n "$VERGE_RAW" ]; then
    echo "$VERGE_RAW" | grep -oE '\u003ch2[^\u003e]*\u003e[^\u003c]{20,100}\u003c/h2\u003e' | \
        sed 's/\u003c[^\u003e]*\u003e//g' | head -3 | while read -r title; do
        [ -n "$title" ] && log "  Verge: ${title:0:60}..." && NEWS_ITEMS="${NEWS_ITEMS}- [Verge] $title\n"
    done
fi

# 4. Reddit r/technology (JSON API)
log "Checking Reddit r/technology..."
REDDIT_JSON=$(curl -sL --max-time 15 "https://www.reddit.com/r/technology/hot.json?limit=5" \
    -H "User-Agent: Mozilla/5.0" 2>/dev/null)
if [ -n "$REDDIT_JSON" ]; then
    echo "$REDDIT_JSON" | jq -r '.data.children[].data.title' 2>/dev/null | head -3 | while read -r title; do
        [ -n "$title" ] && log "  Reddit: ${title:0:60}..." && NEWS_ITEMS="${NEWS_ITEMS}- [Reddit] $title\n"
    done
fi

# Write to diary
DIARY_FILE="$DIARY_DIR/$(date +%Y-%m-%d)-research-live.md"
DATE_STR=$(date '+%Y-%m-%d %H:%M')

cat > "$DIARY_FILE" << EOF
# Research Notes - $DATE_STR

*Live news fetched from actual websites*

## Wikipedia Random Articles

$(echo -e "$WIKI_ARTICLES")

## Live Tech News ($(date +%Y-%m-%d))

$(echo -e "$NEWS_ITEMS")

## Quick Insights

- **Sources**: Hacker News, TechCrunch, The Verge, Reddit r/technology
- **Fetched**: $(date '+%Y-%m-%d %H:%M:%S')
- **Method**: Live HTML scraping + APIs

*What connections or patterns do you see?*

---
*Generated by research cron job - LIVE sources*
EOF

log "Written to $DIARY_FILE"

# Summary
TOTAL_NEWS=$(echo -e "$NEWS_ITEMS" | grep -c "^-" || echo "0")
log "=== Summary ==="
log "Wikipedia articles: 3"
log "Live news items: $TOTAL_NEWS"
log "Sources checked: HN, TechCrunch, The Verge, Reddit"
log "Diary file: $DIARY_FILE"
log "Research complete"
